### ISSUE TITLE
Problems installing on Go1.3

### ISSUE THREAD

**Issue by flexd** [jtolds/go-oauth2http#1]
Hi there.

https://gist.github.com/flexd/9638f654738de2dbaaab

I am getting this error trying to `go get` this package. Any idea what is going on?

**Comment by flexd** [comment]
It would seem oauth2 recently changed it's API. https://github.com/golang/oauth2/commit/a568078818bb97b96ee7c7829b4575b81d4684f1

**Comment by jtolio** [comment]
this is fixed now, right? please reopen if not
